fix(aliasing UB): insert_after takes NonNull instead of &G::EntryType
$ MIRIFLAGS=-Zmiri-tree-borrows cargo miri test
test cursor_front_mut ...
error: Undefined Behavior: write access through <150749> at alloc47238[0x0] is forbidden
   --> tests/cursor.rs:22:9
    |
 22 |         cursor.peek_prev().unwrap().inner = "Hello".to_owned();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the Tree Borrows rules it violated are still
 experimental
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/tree-borrows.md for further information
    = help: the accessed tag <150749> is a child of the conflicting tag <149899>
    = help: the conflicting tag <149899> has state Frozen which forbids this child write access
help: the accessed tag <150749> was created here
   --> tests/cursor.rs:22:9
    |
 22 |         cursor.peek_prev().unwrap().inner = "Hello".to_owned();
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: the conflicting tag <149899> was created here, in the initial state Cell
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l/src/raw_list.rs:127:31
    |
127 |         new_entry.prev = Some(NonNull::from(existing));
    |                               ^^^^^^^^^^^^^^^^^^^^^^^
    = note: BACKTRACE (of the first span) on thread `cursor_front_mu`:
    = note: inside `cursor_front_mut` at tests/cursor.rs:22:9: 22:42
note: inside closure
   --> tests/cursor.rs:9:22
    |
  8 | #[test]
    | ------- in this attribute macro expansion
  9 | fn cursor_front_mut() {
    |                      ^